### ISSUE TITLE
Feature: generate SBOM

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator-go#2] opened 2022-03-25 21:26 UTC
golang's 1.18 will have support for generating SBOM via an API.
We can add this as part of the list of materials generated by the builder.

**Comment by asraa** [comment] 2022-05-02 19:03
Closing as a dupe of slsa-framework/slsa-github-generator#94

**Closed by asraa** 2022-05-02 19:03 UTC
